# 트랜스포머를 이용한 챗봇 실습

In [75]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import re
import urllib.request

 - data_chatbot.csv 다운로드

In [76]:
urllib.request.urlretrieve(
    "http://data.jaen.kr/download?download_path=%2Fdata%2Ffiles%2F%EB%94%A5%EB%9F%AC%EB%8B%9D%2FLIG%2Fdata%2Fdata_chatbot.csv",
    filename="data_chatbot.csv")

('data_chatbot.csv', <http.client.HTTPMessage at 0x20225368190>)

 - data_chatbot.csv을 읽어 df에 저장하세요

In [77]:
# code here


Q                           A  label
0                       12시 땡!\n                \t하루가 또 가네요.      0
1                  1지망 학교 떨어졌어\n                 \t위로해 드립니다.      0
2                 3박4일 놀러가고 싶다\n               \t여행은 언제나 좋죠.      0
3              3박4일 정도 놀러가고 싶다\n               \t여행은 언제나 좋죠.      0
4                      PPL 심하네\n                \t눈살이 찌푸려지죠.      0
...                          ...                         ...    ...
11818           훔쳐보는 것도 눈치 보임.\n        \t티가 나니까 눈치가 보이는 거죠!      2
11819           훔쳐보는 것도 눈치 보임.\n             \t훔쳐보는 거 티나나봐요.      2
11820              흑기사 해주는 짝남.\n                    \t설렜겠어요.      2
11821  힘든 연애 좋은 연애라는게 무슨 차이일까?\n  \t잘 헤어질 수 있는 사이 여부인 거 같아요.      2
11822               힘들어서 결혼할까봐\n        \t도피성 결혼은 하지 않길 바라요.      2

[11823 rows x 3 columns]

- 데이터 프레임의 shape을 조회하세요

In [78]:
# code here


(11823, 3)

- 데이터 프레임의 결측치를 조회하세요

In [79]:
# code here


Q        0
A        0
label    0
dtype: int64

- 데이터 프레임의 정보를 출력하세요

In [80]:
# code here


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11823 entries, 0 to 11822
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Q       11823 non-null  object
 1   A       11823 non-null  object
 2   label   11823 non-null  int64 
dtypes: int64(1), object(2)
memory usage: 277.2+ KB


### 데이터 전처리

 - 구두점을 제거하세요
   - 마침표, 쉼표, 느낌표, 물음표를 공백으로 치환

In [81]:
def remove_punctuations(sentence):
    sentence = re.sub(r'([?.!,])', ' ', sentence)
    return sentence

# code here


Q                           A  label
0                       12시 땡 \n                \t하루가 또 가네요       0
1                  1지망 학교 떨어졌어\n                 \t위로해 드립니다       0
2                 3박4일 놀러가고 싶다\n               \t여행은 언제나 좋죠       0
3              3박4일 정도 놀러가고 싶다\n               \t여행은 언제나 좋죠       0
4                      PPL 심하네\n                \t눈살이 찌푸려지죠       0
...                          ...                         ...    ...
11818           훔쳐보는 것도 눈치 보임 \n        \t티가 나니까 눈치가 보이는 거죠       2
11819           훔쳐보는 것도 눈치 보임 \n             \t훔쳐보는 거 티나나봐요       2
11820              흑기사 해주는 짝남 \n                    \t설렜겠어요       2
11821  힘든 연애 좋은 연애라는게 무슨 차이일까 \n  \t잘 헤어질 수 있는 사이 여부인 거 같아요       2
11822               힘들어서 결혼할까봐\n        \t도피성 결혼은 하지 않길 바라요       2

[11823 rows x 3 columns]

 - 문자열 앞뒤 공백을 제거하세요.

In [82]:
# code here


Q                        A  label
0                       12시 땡                하루가 또 가네요      0
1                 1지망 학교 떨어졌어                 위로해 드립니다      0
2                3박4일 놀러가고 싶다               여행은 언제나 좋죠      0
3             3박4일 정도 놀러가고 싶다               여행은 언제나 좋죠      0
4                     PPL 심하네                눈살이 찌푸려지죠      0
...                       ...                      ...    ...
11818           훔쳐보는 것도 눈치 보임        티가 나니까 눈치가 보이는 거죠      2
11819           훔쳐보는 것도 눈치 보임             훔쳐보는 거 티나나봐요      2
11820              흑기사 해주는 짝남                    설렜겠어요      2
11821  힘든 연애 좋은 연애라는게 무슨 차이일까  잘 헤어질 수 있는 사이 여부인 거 같아요      2
11822              힘들어서 결혼할까봐        도피성 결혼은 하지 않길 바라요      2

[11823 rows x 3 columns]

 - 중복 문자열 개수 확인 및 제거

In [83]:
# code here


3

In [84]:
# code here


(11820, 3)

### 단어 사전 생성 및 토큰화
 - konlpy okt를 이용하여 토큰화하세요.
 - build_vocab_from_iterator를 이용하여 단어 사전을 생성하세요.
 - \<PAD>, \<OOV>, \<SOS>, \<EOS> 토큰을 추가하세요.
   - 기본 토큰은 PAD 입니다.
 - 단어 사전 크기를 출력하세요.

 - Okt Tokenizer를 생성하세요.

In [85]:
# code here


 - 단어 사전을 생성하세요.

In [68]:
# code here


12665

 - 단어 사전을 출력하세요.

In [69]:
# code here


{'나왔나요': 7904,
 '찾아왔나': 11844,
 '썸': 52,
 '즐거운': 725,
 '어리게만': 10583,
 '<EOS>': 3,
 '은': 12,
 '가르쳐': 4558,
 '후련하기도': 12545,
 '놀러': 581,
 '그렇게': 276,
 '현명한': 7036,
 '하잖아요': 12244,
 '봤으면': 3994,
 '빠를수록': 1962,
 '근사한': 7606,
 '찾아줘서': 11846,
 '가볍게': 2846,
 '효율': 7067,
 '아파하고': 4127,
 '보려': 5588,
 '인후': 6352,
 '휴가': 1023,
 '멋있는거': 5390,
 '외국': 10845,
 '그러기': 7546,
 '<PAD>': 0,
 '떠오르니까': 8686,
 '예전': 2311,
 '마시라고': 5273,
 '있어': 124,
 '다행': 591,
 '<OOV>': 1,
 '답답한데': 8295,
 '익숙해질': 3356,
 '씹': 3246,
 '는': 26,
 '이긴': 3344,
 '이미': 1811,
 '아닌': 439,
 '애니': 6114,
 '양말': 1611,
 '너덜너덜해졌어': 8051,
 '거': 7,
 '열심히': 348,
 '살거': 5757,
 '표시': 2403,
 '하겠네': 12192,
 '다시': 96,
 '재미없다': 11313,
 '올라오네': 10803,
 '생각': 18,
 '발표': 912,
 '아니면': 1267,
 '헤어짐도': 4505,
 '이었다는': 11026,
 '고맙다고': 3652,
 '가시': 3610,
 '내': 38,
 '좋아하는': 30,
 '만나야죠': 5295,
 '시급하네요': 5904,
 '<SOS>': 2,
 '서툴어': 9930,
 '디뎠네요': 8638,
 '상이': 4045,
 '이별': 28,
 '청첩장': 1510,
 '붙잡으면': 9646,
 '붙였나': 9632,
 '맛': 514,
 '다닐까': 3773,
 '놈': 856,
 '하래': 69

 - Tokenizer와 사전을 이용하여 모든 문장을 토큰화하세요.
 - 디코더 입력, 레이블 시퀀에 각각 \<SOS>, \<EOS>에 해당하는 인덱스를 추가하세요.
   - 입력 앞 sos
   - 레이블 뒤 eos
 - 토큰화된 데이터를 상위 5개만 출력

In [87]:
# code here


(array([list(['12시', '땡']), list(['1', '지망', '학교', '떨어졌어']),
        list(['3', '박', '4일', '놀러', '가고', '싶다']), ...,
        list(['흑기사', '해주는', '짝남']),
        list(['힘든', '연애', '좋은', '연애', '라는', '게', '무슨', '차이', '일까']),
        list(['힘들어서', '결혼', '할까봐'])], dtype=object),
 array([list(['하루', '가', '또', '가네요']), list(['위로', '해', '드립니다']),
        list(['여행', '은', '언제나', '좋죠']), ..., list(['설렜겠어요']),
        list(['잘', '헤어질', '수', '있는', '사이', '여부', '인', '거', '같아요']),
        list(['도피', '성', '결혼', '은', '하지', '않길', '바라요'])], dtype=object))

In [88]:
# code here


([[4530, 8666],
  [651, 6594, 532, 1244],
  [397, 3118, 2096, 581, 240, 97],
  [397, 3118, 2096, 403, 581, 240, 97],
  [7140, 5962]],
 [[2, 197, 5, 103, 2838],
  [2, 296, 37, 3032],
  [2, 223, 12, 691, 181],
  [2, 223, 12, 691, 181],
  [2, 4976, 4, 6663]],
 [[197, 5, 103, 2838, 3],
  [296, 37, 3032, 3],
  [223, 12, 691, 181, 3],
  [223, 12, 691, 181, 3],
  [4976, 4, 6663, 3]])

### 패딩
 - 토큰화된 시퀀스를 가장 긴 시퀀스에 맞춰 Post 패딩하세요.

In [91]:
# code here


In [92]:
# code here


(tensor([[ 4530,  8666,     0,  ...,     0,     0,     0],
         [  651,  6594,   532,  ...,     0,     0,     0],
         [  397,  3118,  2096,  ...,     0,     0,     0],
         ...,
         [12589,   851,    94,  ...,     0,     0,     0],
         [  162,    74,    44,  ...,     0,     0,     0],
         [ 1315,   111,  4476,  ...,     0,     0,     0]]),
 tensor([[   2,  197,    5,  ...,    0,    0,    0],
         [   2,  296,   37,  ...,    0,    0,    0],
         [   2,  223,   12,  ...,    0,    0,    0],
         ...,
         [   2, 9957,    0,  ...,    0,    0,    0],
         [   2,   19, 1859,  ...,    0,    0,    0],
         [   2, 5094, 1259,  ...,    0,    0,    0]]),
 tensor([[ 197,    5,  103,  ...,    0,    0,    0],
         [ 296,   37, 3032,  ...,    0,    0,    0],
         [ 223,   12,  691,  ...,    0,    0,    0],
         ...,
         [9957,    3,    0,  ...,    0,    0,    0],
         [  19, 1859,   24,  ...,    0,    0,    0],
         [5094, 1

In [93]:
# code here


(torch.Size([11820, 30]), torch.Size([11820, 30]), torch.Size([11820, 30]))

### Transformer 모델링

 - 학습, 검증 데이터로 분할하세요. 분할 비율은 8:2로 설정하세요.

In [94]:
# code here


(torch.Size([9456, 30]),
 torch.Size([2364, 30]),
 torch.Size([9456, 30]),
 torch.Size([2364, 30]),
 torch.Size([9456, 30]),
 torch.Size([2364, 30]))

In [95]:
import torch
from torch import nn, optim
from torch.nn import functional as F

 - CustomDataset을 구현하고 학습, 검증 데이터 셋을 생성하세요.

In [96]:
# code here


 - DataLoader를 생성하세요.
   - Batch Size: 128

In [97]:
# code here


 - TransformerModel 모델 클래스를 생성하세요.
     - nn.Transformer 모듈을 이용하세요.
     - PositionalEncoding, PositionalEmbedding 모듈을 구현하세요.

In [98]:
# code here


In [99]:
# code here


In [110]:
# code here


- gpu 사용 가능 여부를 확인하여 device를 설정하세요.

In [111]:
# code here


'cuda'

 - TransformerModel 모델 인스턴스를 생성하세요.
   - d_model=d_embed=256
   - d_ff=512
   - n_heads=8
   - n_layers=2
   - dropout=0.1
 - 모델 요약을 출력하세요.

In [112]:
# code here


In [113]:
# code here


Layer (type:depth-idx)                                                 Param #
TransformerModel                                                       --
├─PositionalEmbedding: 1-1                                             --
│    └─Embedding: 2-1                                                  3,242,240
│    └─PositionalEncoding: 2-2                                         --
│    │    └─Dropout: 3-1                                               --
├─PositionalEmbedding: 1-2                                             --
│    └─Embedding: 2-3                                                  3,242,240
│    └─PositionalEncoding: 2-4                                         --
│    │    └─Dropout: 3-2                                               --
├─Transformer: 1-3                                                     --
│    └─TransformerEncoder: 2-5                                         --
│    │    └─ModuleList: 3-3                                            1,054,208
│    │    └─

 - CrossEntropyLoss와 Adam Optimizer를 생성하세요.
   - 손실 함수에 ignore_index를 지정
   - 최적화 도구에 lr=1, eps=1e-9, betas=(0.9, 0.98)

In [114]:
# code here


 - 커스텀 학습률 스케줄러를 생성하세요

In [115]:
# 제공된 코드를 그대로 이용하세요.
class WarmupLRScheduler(optim.lr_scheduler.LambdaLR):
    def __init__(self, optimizer, d_model,  warmup_steps, last_epoch=-1):
        def lambda_lr(step):
            arg1 = step**-0.5 if step > 0 else 0
            arg2 = step * (warmup_steps ** -1.5)
            return (d_model**-0.5) * min(arg1, arg2)
        super().__init__(optimizer, lambda_lr, last_epoch=last_epoch)

In [116]:
# 제공된 코드를 그대로 이용하세요.
d_model=256
warmup_steps=4000
scheduler = WarmupLRScheduler(optimizer, d_model, warmup_steps)

 - 학습 데이터와 검증 데이터를 이용하여 모델을 학습시키세요.

In [117]:
# code here


  0%|          | 0/50 [00:00<?, ?it/s]

 - 챗봇 예측 함수를 구현하여 실행하세요.

In [118]:
def predict(x_input, target_len=30):
    # code here
    
    return outputs

In [119]:
# code here


질문: 12시 땡
응답: 하루 가 또 가네요


In [120]:
# code here


질문: 12시 땡
응답: 여행 은 언제나 좋죠


In [121]:
# code here


질문: 12시 땡
응답: 눈살 이 찌푸려지죠
